# Generated by Django 2.0.6 on 2018-06-25 04:35

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_postcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ['-commented_at'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.RenameField(
            model_name='aboutpage',
            old_name='body',
            new_name='body_en',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='body_th',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='post',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='blog.PostPage'),
        ),
    ]
