# Generated by Django 2.0.6 on 2018-08-03 07:06

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('blog', '0014_auto_20180703_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('title_en', wagtail.core.fields.RichTextField(blank=True)),
                ('title_th', wagtail.core.fields.RichTextField(blank=True)),
                ('description_en', models.CharField(blank=True, max_length=255)),
                ('description_th', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
