# Generated by Django 2.0.6 on 2018-08-05 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_homepagelink_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagelink',
            old_name='url',
            new_name='pageurl',
        ),
    ]
