"""added affil field

Revision ID: 0ce6845adce3
Revises: 18a5b732eea6
Create Date: 2018-08-08 10:11:58.644852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ce6845adce3'
down_revision = '18a5b732eea6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scholarship_info', sa.Column('affil', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scholarship_info', 'affil')
    # ### end Alembic commands ###
