"""added email to scholarship info

Revision ID: 5473557e57ce
Revises: 9164d7101ce1
Create Date: 2019-04-25 09:37:16.822393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5473557e57ce'
down_revision = '9164d7101ce1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scholarship_info', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scholarship_info', 'email')
    # ### end Alembic commands ###
