"""added affil_scopus_id to keywords model

Revision ID: 6ab74342e882
Revises: aa93e8a6bb6e
Create Date: 2018-06-24 21:48:01.628564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ab74342e882'
down_revision = 'aa93e8a6bb6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keywords', sa.Column('affil_scopus_id', sa.String(length=32), nullable=True))
    op.add_column('keywords', sa.Column('author_scopus_id', sa.String(length=64), nullable=True))
    op.drop_column('keywords', 'scopus_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keywords', sa.Column('scopus_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('keywords', 'author_scopus_id')
    op.drop_column('keywords', 'affil_scopus_id')
    # ### end Alembic commands ###
