"""added ST student_id field

Revision ID: 98af32e2c860
Revises: ee466cca8d4d
Create Date: 2019-04-25 05:11:54.956039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98af32e2c860'
down_revision = 'ee466cca8d4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('gjb_researcher_profile_author_id_fkey', 'gjb_researcher_profile', type_='foreignkey')
    op.drop_column('gjb_researcher_profile', 'author_id')
    op.add_column('scholarship_info', sa.Column('student_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'scholarship_info', ['student_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scholarship_info', type_='unique')
    op.drop_column('scholarship_info', 'student_id')
    op.add_column('gjb_researcher_profile', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('gjb_researcher_profile_author_id_fkey', 'gjb_researcher_profile', 'authors', ['author_id'], ['id'])
    # ### end Alembic commands ###
