"""removed abstractid field from noun chunk

Revision ID: 9a7c3fab69f3
Revises: 5b453f7b5fc1
Create Date: 2018-06-25 00:03:56.101817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a7c3fab69f3'
down_revision = '5b453f7b5fc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('noun_chunks_abstract_id_fkey', 'noun_chunks', type_='foreignkey')
    op.drop_column('noun_chunks', 'abstract_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noun_chunks', sa.Column('abstract_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('noun_chunks_abstract_id_fkey', 'noun_chunks', 'abstracts', ['abstract_id'], ['id'])
    # ### end Alembic commands ###
