"""added many-to-many between abstracts and authors

Revision ID: d0283825b287
Revises: b9126b0b23f7
Create Date: 2018-06-25 00:43:44.850812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0283825b287'
down_revision = 'b9126b0b23f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abstract_has_author',
    sa.Column('abstract_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['abstract_id'], ['abstracts.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('abstract_has_author')
    # ### end Alembic commands ###
