"""removed the profile_id field

Revision ID: ee466cca8d4d
Revises: 09230cb065cf
Create Date: 2018-10-07 13:39:29.390103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee466cca8d4d'
down_revision = '09230cb065cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('gjb_researcher_profile_profile_id_key', 'gjb_researcher_profile', type_='unique')
    op.drop_column('gjb_researcher_profile', 'profile_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gjb_researcher_profile', sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_unique_constraint('gjb_researcher_profile_profile_id_key', 'gjb_researcher_profile', ['profile_id'])
    # ### end Alembic commands ###
