version: '3'

services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    env_file:
      - ./wordpress.env
    volumes:
      - ./wordpress:/var/www/html
  wpdb:
    image: mysql:5.7
    restart: always
    env_file:
      - ./wordpress.env
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=talent
    volumes:
      - tm_wordpress:/var/lib/mysql
  mysql_db:
    image: mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    restart: always
    volumes:
      - ./msql-data:/var/lib/mysql
  metabase:
    image: metabase/metabase
    ports:
      - "3000:3000"
    volumes:
      - ./metabase-data:/metabase-data
    environment:
      - MB_DATA_FILE="/metabase-data/metabase.db"
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=postgres
      - MB_DB_HOST=postgres_db
      - MB_DB_PASS
  neo4j_db:
    image: neo4j
    volumes:
      - ./neo_data:/data
    ports:
      - "7474:7474"
      - "7687:7687"
  postgres_db:
    image: postgres:10
    volumes:
      - ./pg_data:/var/lib/postgresql/data/
    ports:
      - "5434:5432"
  warehouse:
    build: ./warehouse
    volumes:
      - ./warehouse/app:/app
    env_file:
      - ./warehouse/variables.env
    depends_on:
      - postgres_db
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 -w 2 --threads=2  tm.wsgi
    environment:
      - EMAIL_PASSWORD=$EMAIL_PASSWORD
    volumes:
      - ./code:/code
    ports:
      - "8000:8000"
      - "80:8000"
    depends_on:
      - postgres_db
      - neo4j_db
  analytics:
    build: './analytics'
    environment:
      - FLASK_APP
      - FLASK_DEBUG
    command: gunicorn --bind 0.0.0.0:5500 -w 2 app:app --threads=2
    volumes:
      - ./analytics/code:/code
    ports:
      - "5500:5500"
    depends_on:
      - postgres_db

volumes:
  pg_data:
  tm_wordpress:
