version: '3'

services:
  metabase:
    image: metabase/metabase
    ports:
      - "3000:3000"
    volumes:
      - ./metabase-data:/metabase-data
    environment:
      - MB_DATA_FILE="/metabase-data/metabase.db"
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=postgres
      - MB_DB_HOST=postgres_db
      - MB_DB_PASS
  neo4j_db:
    image: neo4j
    volumes:
      - ./neo_data:/data
    ports:
      - "7474:7474"
      - "7687:7687"
  postgres_db:
    image: postgres
    volumes:
      - ./pg_data:/var/lib/postgresql/data/
    ports:
      - "5434:5432"
  web:
    build: .
    command: python tm/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./code:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
      - neo4j_db

volumes:
  pg_data:
