version: '3'

services:
  postgres_db:
    image: postgres
    volumes:
      - ./pg_data:/var/lib/postgresql/data/
  web:
    build: .
    command: python talentda/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./code:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db

volumes:
  pg_data: