version: '3'

services:
  neo4j_db:
    image: neo4j
    volumes:
      - ./neo_data:/data
    ports:
      - "7474:7474"
      - "7687:7687"
  postgres_db:
    image: postgres
    volumes:
      - ./pg_data:/var/lib/postgresql/data/
    ports:
      - "5434:5432"
  web:
    build: .
    command: python tm/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./code:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db

volumes:
  pg_data:
