"""added affil ID to author list

Revision ID: 7de37ecc0035
Revises: 94df9a1e85b5
Create Date: 2018-10-07 16:28:28.103749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7de37ecc0035'
down_revision = '94df9a1e85b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affils',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scopus_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('author_lists', sa.Column('affil_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'author_lists', 'affils', ['affil_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'author_lists', type_='foreignkey')
    op.drop_column('author_lists', 'affil_id')
    op.drop_table('affils')
    # ### end Alembic commands ###
