"""add some initial models

Revision ID: 94df9a1e85b5
Revises: 
Create Date: 2018-10-07 15:40:55.995036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94df9a1e85b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abstracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('title_en', sa.Text(), nullable=True),
    sa.Column('abstract_en', sa.Text(), nullable=True),
    sa.Column('title_th', sa.Text(), nullable=True),
    sa.Column('abstract_th', sa.Text(), nullable=True),
    sa.Column('scopus_id', sa.String(length=32), nullable=False),
    sa.Column('cited', sa.Integer(), nullable=True),
    sa.Column('pub_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scopus_id')
    )
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('scopus_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abbr', sa.String(length=8), nullable=True),
    sa.Column('fullname', sa.String(length=64), nullable=True),
    sa.Column('scopus_id', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('author_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('field_pubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=True),
    sa.Column('abstract_id', sa.Integer(), nullable=True),
    sa.Column('author_list_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['abstract_id'], ['abstracts.id'], ),
    sa.ForeignKeyConstraint(['author_list_id'], ['author_lists.id'], ),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('field_pubs')
    op.drop_table('author_lists')
    op.drop_table('fields')
    op.drop_table('authors')
    op.drop_table('abstracts')
    # ### end Alembic commands ###
