"""added keywords and noun chunk models

Revision ID: 9e5a55e7582b
Revises: a93ed615b998
Create Date: 2018-10-07 19:19:47.788591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e5a55e7582b'
down_revision = 'a93ed615b998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('noun_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chunk_en', sa.String(length=255), nullable=False),
    sa.Column('chunk_th', sa.String(length=255), nullable=False),
    sa.Column('is_auth_keywords', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_en', sa.String(length=64), nullable=False),
    sa.Column('word_th', sa.String(length=64), nullable=False),
    sa.Column('abstract_id', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['abstract_id'], ['abstracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keywords_word_en'), 'keywords', ['word_en'], unique=False)
    op.create_index(op.f('ix_keywords_word_th'), 'keywords', ['word_th'], unique=False)
    op.create_table('nounchunk_has_keyword',
    sa.Column('noun_chunk_id', sa.Integer(), nullable=True),
    sa.Column('keyword_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.ForeignKeyConstraint(['noun_chunk_id'], ['noun_chunks.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nounchunk_has_keyword')
    op.drop_index(op.f('ix_keywords_word_th'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_word_en'), table_name='keywords')
    op.drop_table('keywords')
    op.drop_table('noun_chunks')
    # ### end Alembic commands ###
