"""added gjb researcher model

Revision ID: cf68bab4b975
Revises: e3731a81fcaa
Create Date: 2018-10-08 07:39:05.998117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf68bab4b975'
down_revision = 'e3731a81fcaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
