# Generated by Django 2.0.6 on 2018-07-03 14:01

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_postpage_feed_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postpage',
            old_name='body',
            new_name='body_en',
        ),
        migrations.AddField(
            model_name='postpage',
            name='body_th',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
