# Generated by Django 2.0.6 on 2018-07-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_postpage_title_th'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='description',
            new_name='description_en',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='description_th',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='title_en',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
