# Generated by Django 2.0.6 on 2018-07-03 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20180703_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='title_en',
            new_name='title_th',
        ),
    ]
