# Generated by Django 2.0.6 on 2018-08-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_portalpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portalpage',
            name='title_en',
        ),
        migrations.AlterField(
            model_name='portalpage',
            name='title_th',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
