# Generated by Django 2.0.6 on 2018-08-05 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('blog', '0016_auto_20180803_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageLink',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('title_th', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(blank=True, max_length=64)),
                ('description_en', models.CharField(blank=True, max_length=255)),
                ('description_th', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
