# Generated by Django 2.0.6 on 2018-08-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_homepagelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagelink',
            name='url',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
