"""created the publication model

Revision ID: e18b784e5af8
Revises: 
Create Date: 2019-07-03 15:50:36.197524

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e18b784e5af8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scopus_id', sa.String(length=32), nullable=True),
    sa.Column('doctype', sa.String(length=8), nullable=True),
    sa.Column('pub_date', sa.Date(), nullable=True),
    sa.Column('cited_count', sa.Integer(), nullable=True),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pubs_scopus_id'), 'pubs', ['scopus_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pubs_scopus_id'), table_name='pubs')
    op.drop_table('pubs')
    # ### end Alembic commands ###
