# Generated by Django 2.0.6 on 2018-06-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='scholarship',
            field=models.BooleanField(default=False),
        ),
    ]
