# Generated by Django 2.0.6 on 2018-06-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180623_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='degree',
            field=models.IntegerField(blank=True, choices=[(1, 'ปริญญาตรี'), (2, 'ปริญญาโท'), (3, 'ปริญญาเอก')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='graduated_at',
            field=models.DateField(blank=True),
        ),
    ]
