# Generated by Django 2.0.6 on 2018-06-24 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20180624_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='user',
        ),
        migrations.DeleteModel(
            name='PostComment',
        ),
    ]
