# Generated by Django 2.0.6 on 2018-06-23 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_th', models.CharField(max_length=255)),
                ('last_name_th', models.CharField(max_length=255)),
                ('college', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('degree', models.IntegerField(blank=True, choices=[('1', 'ปริญญาตรี'), ('2', 'ปริญญาโท'), ('3', 'ปริญญาเอก')])),
                ('graduate_at', models.DateTimeField(blank=True)),
                ('field_of_study', models.CharField(blank=True, max_length=255)),
                ('specialty', models.CharField(blank=True, max_length=255)),
                ('designated_affiliation', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d')),
                ('current_position', models.CharField(blank=True, max_length=255)),
                ('current_affiliation', models.CharField(blank=True, max_length=255)),
                ('about', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
