# Generated by Django 2.0.6 on 2018-06-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='degree',
            field=models.IntegerField(blank=True, choices=[(1, 'ปริญญาตรี'), (2, 'ปริญญาโท'), (3, 'ปริญญาเอก')], null=True),
        ),
    ]
