# Generated by Django 2.0.6 on 2018-06-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20180623_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='graduated_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
