# Generated by Django 2.0.6 on 2018-06-25 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20180624_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='scopus_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
