# Generated by Django 2.0.6 on 2018-08-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_profile_field_of_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tm_profile_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
