"""added frequency field to the bridge scopus field group

Revision ID: 066e1e132095
Revises: a6b8e1c2db9f
Create Date: 2019-12-30 04:05:41.647215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '066e1e132095'
down_revision = 'a6b8e1c2db9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('br_scopus_field_group', sa.Column('frequency', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('br_scopus_field_group', 'frequency')
    # ### end Alembic commands ###
