"""added scopus field group ID field to the fact table

Revision ID: 08aa56d41945
Revises: 746a768e67ad
Create Date: 2019-12-29 09:25:48.401601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08aa56d41945'
down_revision = '746a768e67ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_scopus_field_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('br_scopus_field_group',
    sa.Column('scopus_field_group_id', sa.Integer(), nullable=False),
    sa.Column('scopus_field_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scopus_field_group_id'], ['dim_scopus_field_groups.id'], ),
    sa.ForeignKeyConstraint(['scopus_field_id'], ['dim_scopus_fields.id'], ),
    sa.PrimaryKeyConstraint('scopus_field_group_id', 'scopus_field_id')
    )
    op.add_column('fact_researchers', sa.Column('sc_field_group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fact_researchers', 'dim_scopus_field_groups', ['sc_field_group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fact_researchers', type_='foreignkey')
    op.drop_column('fact_researchers', 'sc_field_group_id')
    op.drop_table('br_scopus_field_group')
    op.drop_table('dim_scopus_field_groups')
    # ### end Alembic commands ###
