"""added academic position field to the researcher table

Revision ID: 1be024416046
Revises: 8c7869a44ae0
Create Date: 2019-12-22 13:32:14.208593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1be024416046'
down_revision = '8c7869a44ae0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fact_researchers', sa.Column('academic_position_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fact_researchers', 'dim_academic_positions', ['academic_position_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fact_researchers', type_='foreignkey')
    op.drop_column('fact_researchers', 'academic_position_id')
    # ### end Alembic commands ###
