"""added dim scopus author detail

Revision ID: 34d15f0fb644
Revises: 08aa56d41945
Create Date: 2019-12-30 02:33:57.448654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34d15f0fb644'
down_revision = '08aa56d41945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_scopus_author_detail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('author_id', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('coauthor_count', sa.Integer(), nullable=True),
    sa.Column('h_index', sa.Integer(), nullable=True),
    sa.Column('pub_start', sa.Date(), nullable=True),
    sa.Column('pub_end', sa.Date(), nullable=True),
    sa.Column('current', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=True),
    sa.Column('cited_by_count', sa.Integer(), nullable=True),
    sa.Column('affiliation', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('scopus_field_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scopus_field_group_id'], ['dim_scopus_field_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dim_scopus_author_detail')
    # ### end Alembic commands ###
