"""added some more dimensions

Revision ID: 3dbdb83a3a91
Revises: 2950cb029279
Create Date: 2019-12-22 10:24:14.889634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dbdb83a3a91'
down_revision = '2950cb029279'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_academic_positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_academic_positions_title'), 'dim_academic_positions', ['title'], unique=False)
    op.create_table('dim_email',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_email_email'), 'dim_email', ['email'], unique=False)
    op.create_table('dim_eng_names',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('initial', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_eng_names_firstname'), 'dim_eng_names', ['firstname'], unique=False)
    op.create_index(op.f('ix_dim_eng_names_initial'), 'dim_eng_names', ['initial'], unique=False)
    op.create_index(op.f('ix_dim_eng_names_lastname'), 'dim_eng_names', ['lastname'], unique=False)
    op.create_table('dim_thai_names',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_thai_names_firstname'), 'dim_thai_names', ['firstname'], unique=False)
    op.create_index(op.f('ix_dim_thai_names_lastname'), 'dim_thai_names', ['lastname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dim_thai_names_lastname'), table_name='dim_thai_names')
    op.drop_index(op.f('ix_dim_thai_names_firstname'), table_name='dim_thai_names')
    op.drop_table('dim_thai_names')
    op.drop_index(op.f('ix_dim_eng_names_lastname'), table_name='dim_eng_names')
    op.drop_index(op.f('ix_dim_eng_names_initial'), table_name='dim_eng_names')
    op.drop_index(op.f('ix_dim_eng_names_firstname'), table_name='dim_eng_names')
    op.drop_table('dim_eng_names')
    op.drop_index(op.f('ix_dim_email_email'), table_name='dim_email')
    op.drop_table('dim_email')
    op.drop_index(op.f('ix_dim_academic_positions_title'), table_name='dim_academic_positions')
    op.drop_table('dim_academic_positions')
    # ### end Alembic commands ###
