"""added scopus author detail group and bridge tables

Revision ID: 5975cb87844c
Revises: cc0f4f989789
Create Date: 2020-01-18 15:56:40.813502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5975cb87844c'
down_revision = 'cc0f4f989789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_scopus_author_detail_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('br_scopus_author_detail_group',
    sa.Column('scopus_author_detail_group_id', sa.Integer(), nullable=False),
    sa.Column('scopus_author_detail_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scopus_author_detail_group_id'], ['dim_scopus_author_detail_groups.id'], ),
    sa.ForeignKeyConstraint(['scopus_author_detail_id'], ['dim_scopus_author_detail.id'], ),
    sa.PrimaryKeyConstraint('scopus_author_detail_group_id')
    )
    op.add_column('dim_scopus_author_detail', sa.Column('en_firstname', sa.String(), nullable=True))
    op.add_column('dim_scopus_author_detail', sa.Column('en_lastname', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dim_scopus_author_detail', 'en_lastname')
    op.drop_column('dim_scopus_author_detail', 'en_firstname')
    op.drop_table('br_scopus_author_detail_group')
    op.drop_table('dim_scopus_author_detail_groups')
    # ### end Alembic commands ###
