"""added scholarship-related fields to the fact table

Revision ID: 722bce41fec9
Revises: a390c91cc24a
Create Date: 2019-12-23 00:24:04.544618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '722bce41fec9'
down_revision = 'a390c91cc24a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_sc_countries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_sc_countries_name'), 'dim_sc_countries', ['name'], unique=False)
    op.create_table('dim_sc_universities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_sc_universities_name'), 'dim_sc_universities', ['name'], unique=False)
    op.add_column('fact_researchers', sa.Column('sc_country_id', sa.Integer(), nullable=True))
    op.add_column('fact_researchers', sa.Column('sc_field', sa.String(), nullable=True))
    op.add_column('fact_researchers', sa.Column('sc_graduated_year', sa.Date(), nullable=True))
    op.add_column('fact_researchers', sa.Column('sc_specialty', sa.String(), nullable=True))
    op.add_column('fact_researchers', sa.Column('sc_university_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fact_researchers', 'dim_sc_countries', ['sc_country_id'], ['id'])
    op.create_foreign_key(None, 'fact_researchers', 'dim_sc_universities', ['sc_university_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fact_researchers', type_='foreignkey')
    op.drop_constraint(None, 'fact_researchers', type_='foreignkey')
    op.drop_column('fact_researchers', 'sc_university_id')
    op.drop_column('fact_researchers', 'sc_specialty')
    op.drop_column('fact_researchers', 'sc_graduated_year')
    op.drop_column('fact_researchers', 'sc_field')
    op.drop_column('fact_researchers', 'sc_country_id')
    op.drop_index(op.f('ix_dim_sc_universities_name'), table_name='dim_sc_universities')
    op.drop_table('dim_sc_universities')
    op.drop_index(op.f('ix_dim_sc_countries_name'), table_name='dim_sc_countries')
    op.drop_table('dim_sc_countries')
    # ### end Alembic commands ###
