"""renamed scopus_fields table to dim_scopus_fields

Revision ID: 746a768e67ad
Revises: 1ed63a372ad3
Create Date: 2019-12-29 09:17:25.114601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '746a768e67ad'
down_revision = '1ed63a372ad3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_scopus_fields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('abbrev', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('detail', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.drop_table('scopus_fields')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scopus_fields',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('abbrev', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('detail', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='scopus_fields_pkey'),
    sa.UniqueConstraint('code', name='scopus_fields_code_key')
    )
    op.drop_table('dim_scopus_fields')
    # ### end Alembic commands ###
