"""added dim email group and bridge table

Revision ID: 8c7869a44ae0
Revises: 3dbdb83a3a91
Create Date: 2019-12-22 13:24:54.622863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c7869a44ae0'
down_revision = '3dbdb83a3a91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_email_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('br_email_group',
    sa.Column('email_group_id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['email_group_id'], ['dim_email_group.id'], ),
    sa.ForeignKeyConstraint(['email_id'], ['dim_email.id'], ),
    sa.PrimaryKeyConstraint('email_group_id', 'email_id')
    )
    op.create_table('fact_researchers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['email_group_id'], ['dim_email_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fact_researchers')
    op.drop_table('br_email_group')
    op.drop_table('dim_email_group')
    # ### end Alembic commands ###
