"""added scopus author detail ID to the fact researcher table

Revision ID: cc0f4f989789
Revises: 066e1e132095
Create Date: 2019-12-30 04:33:53.859196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc0f4f989789'
down_revision = '066e1e132095'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dim_scopus_author_detail_scopus_field_group_id_fkey', 'dim_scopus_author_detail', type_='foreignkey')
    op.drop_column('dim_scopus_author_detail', 'scopus_field_group_id')
    op.add_column('fact_researchers', sa.Column('scopus_author_detail_id', sa.Integer(), nullable=True))
    op.add_column('fact_researchers', sa.Column('scopus_field_group_id', sa.Integer(), nullable=True))
    op.drop_constraint('fact_researchers_sc_field_group_id_fkey', 'fact_researchers', type_='foreignkey')
    op.create_foreign_key(None, 'fact_researchers', 'dim_scopus_author_detail', ['scopus_author_detail_id'], ['id'])
    op.create_foreign_key(None, 'fact_researchers', 'dim_scopus_field_groups', ['scopus_field_group_id'], ['id'])
    op.drop_column('fact_researchers', 'sc_field_group_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fact_researchers', sa.Column('sc_field_group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'fact_researchers', type_='foreignkey')
    op.drop_constraint(None, 'fact_researchers', type_='foreignkey')
    op.create_foreign_key('fact_researchers_sc_field_group_id_fkey', 'fact_researchers', 'dim_scopus_field_groups', ['sc_field_group_id'], ['id'])
    op.drop_column('fact_researchers', 'scopus_field_group_id')
    op.drop_column('fact_researchers', 'scopus_author_detail_id')
    op.add_column('dim_scopus_author_detail', sa.Column('scopus_field_group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('dim_scopus_author_detail_scopus_field_group_id_fkey', 'dim_scopus_author_detail', 'dim_scopus_field_groups', ['scopus_field_group_id'], ['id'])
    # ### end Alembic commands ###
