"""added the English name group field to the researcher table

Revision ID: d62f0f442a36
Revises: f8271f98cd62
Create Date: 2019-12-22 14:06:40.356736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd62f0f442a36'
down_revision = 'f8271f98cd62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_eng_name_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('br_eng_name_groups',
    sa.Column('en_name_id', sa.Integer(), nullable=False),
    sa.Column('en_name_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['en_name_group_id'], ['dim_eng_name_groups.id'], ),
    sa.ForeignKeyConstraint(['en_name_id'], ['dim_eng_names.id'], ),
    sa.PrimaryKeyConstraint('en_name_id', 'en_name_group_id')
    )
    op.add_column('fact_researchers', sa.Column('en_name_group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fact_researchers', 'dim_eng_name_groups', ['en_name_group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fact_researchers', type_='foreignkey')
    op.drop_column('fact_researchers', 'en_name_group_id')
    op.drop_table('br_eng_name_groups')
    op.drop_table('dim_eng_name_groups')
    # ### end Alembic commands ###
