"""added document count field

Revision ID: de5332e18490
Revises: 30b31d2baf01
Create Date: 2019-12-30 03:20:28.487335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de5332e18490'
down_revision = '30b31d2baf01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dim_scopus_author_detail', sa.Column('document_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dim_scopus_author_detail', 'document_count')
    # ### end Alembic commands ###
