"""changed author detail ID column to author detail group ID to accommodate for multiple author profiles

Revision ID: dedf61559215
Revises: 5975cb87844c
Create Date: 2020-01-18 16:03:40.001948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dedf61559215'
down_revision = '5975cb87844c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fact_researchers', sa.Column('scopus_author_detail_groups_id', sa.Integer(), nullable=True))
    op.drop_constraint('fact_researchers_scopus_author_detail_id_fkey', 'fact_researchers', type_='foreignkey')
    op.create_foreign_key(None, 'fact_researchers', 'dim_scopus_author_detail_groups', ['scopus_author_detail_groups_id'], ['id'])
    op.drop_column('fact_researchers', 'scopus_author_detail_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fact_researchers', sa.Column('scopus_author_detail_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'fact_researchers', type_='foreignkey')
    op.create_foreign_key('fact_researchers_scopus_author_detail_id_fkey', 'fact_researchers', 'dim_scopus_author_detail', ['scopus_author_detail_id'], ['id'])
    op.drop_column('fact_researchers', 'scopus_author_detail_groups_id')
    # ### end Alembic commands ###
