"""added Thai name id field to the researcher table

Revision ID: f8271f98cd62
Revises: 78df3d6383a6
Create Date: 2019-12-22 14:01:39.320746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8271f98cd62'
down_revision = '78df3d6383a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_thai_name_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('br_thai_name_groups',
    sa.Column('thname_id', sa.Integer(), nullable=False),
    sa.Column('thname_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['thname_group_id'], ['dim_thai_name_groups.id'], ),
    sa.ForeignKeyConstraint(['thname_id'], ['dim_thai_names.id'], ),
    sa.PrimaryKeyConstraint('thname_id', 'thname_group_id')
    )
    op.add_column('fact_researchers', sa.Column('thname_group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fact_researchers', 'dim_thai_name_groups', ['thname_group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fact_researchers', type_='foreignkey')
    op.drop_column('fact_researchers', 'thname_group_id')
    op.drop_table('br_thai_name_groups')
    op.drop_table('dim_thai_name_groups')
    # ### end Alembic commands ###
