"""added field_pub_id to the AuthorList

Revision ID: a93ed615b998
Revises: 7de37ecc0035
Create Date: 2018-10-07 16:57:30.376472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a93ed615b998'
down_revision = '7de37ecc0035'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author_lists', sa.Column('field_pub_id', sa.Integer(), nullable=True))
    op.create_foreign_key('author_lists_field_pub_id_fkey', 'author_lists', 'field_pubs', ['field_pub_id'], ['id'])
    op.drop_constraint('field_pubs_author_list_id_fkey', 'field_pubs', type_='foreignkey')
    op.drop_column('field_pubs', 'author_list_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('field_pubs', sa.Column('author_list_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('field_pubs_author_list_id_fkey', 'field_pubs', 'author_lists', ['author_list_id'], ['id'])
    op.drop_constraint('author_lists_field_pub_id_fkey', 'author_lists', type_='foreignkey')
    op.drop_column('author_lists', 'field_pub_id')
    # ### end Alembic commands ###
