"""added authorID to the GJB researcher model

Revision ID: 09230cb065cf
Revises: 7bb5aef25e79
Create Date: 2018-10-07 08:39:13.263327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09230cb065cf'
down_revision = '7bb5aef25e79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gjb_researcher_profile', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'gjb_researcher_profile', 'authors', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gjb_researcher_profile', type_='foreignkey')
    op.drop_column('gjb_researcher_profile', 'author_id')
    # ### end Alembic commands ###
