"""linked author with scholarship model

Revision ID: 09dabab336ea
Revises: d0283825b287
Create Date: 2018-06-28 10:30:10.399890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09dabab336ea'
down_revision = 'd0283825b287'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scholarship_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name_en', sa.String(length=255), nullable=True),
    sa.Column('last_name_en', sa.String(length=255), nullable=True),
    sa.Column('first_name_th', sa.String(length=255), nullable=True),
    sa.Column('last_name_th', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('field_of_study', sa.String(), nullable=True),
    sa.Column('specialty', sa.String(), nullable=True),
    sa.Column('degree', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('authors', sa.Column('scholarship_info_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'authors', 'scholarship_info', ['scholarship_info_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'authors', type_='foreignkey')
    op.drop_column('authors', 'scholarship_info_id')
    op.drop_table('scholarship_info')
    # ### end Alembic commands ###
