"""rename abstract to abstract_en

Revision ID: 1918a9c4e971
Revises: 42afff1828d1
Create Date: 2018-06-24 16:33:41.860569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1918a9c4e971'
down_revision = '42afff1828d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abstracts', sa.Column('abstract_en', sa.Text(), nullable=True))
    op.drop_column('abstracts', 'abstract')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abstracts', sa.Column('abstract', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('abstracts', 'abstract_en')
    # ### end Alembic commands ###
