"""added some more fields to the abstract model

Revision ID: 24f4f609bac5
Revises: a50bd2503a2a
Create Date: 2018-06-24 16:23:37.516857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24f4f609bac5'
down_revision = 'a50bd2503a2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abstracts', sa.Column('abstract', sa.Text(), nullable=True))
    op.add_column('abstracts', sa.Column('cited', sa.Integer(), nullable=True))
    op.add_column('abstracts', sa.Column('pub_date', sa.Date(), nullable=True))
    op.add_column('abstracts', sa.Column('scopus_id', sa.String(length=32), nullable=False))
    op.add_column('abstracts', sa.Column('title', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'abstracts', ['scopus_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'abstracts', type_='unique')
    op.drop_column('abstracts', 'title')
    op.drop_column('abstracts', 'scopus_id')
    op.drop_column('abstracts', 'pub_date')
    op.drop_column('abstracts', 'cited')
    op.drop_column('abstracts', 'abstract')
    # ### end Alembic commands ###
