"""added scopus id to keywords model

Revision ID: 312b6e3b1a7c
Revises: 722b1410041c
Create Date: 2018-06-24 21:02:34.999220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '312b6e3b1a7c'
down_revision = '722b1410041c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keywords', sa.Column('scopus_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('keywords', 'scopus_id')
    # ### end Alembic commands ###
