"""rename title column to title_en

Revision ID: 42afff1828d1
Revises: 24f4f609bac5
Create Date: 2018-06-24 16:32:53.329474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42afff1828d1'
down_revision = '24f4f609bac5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abstracts', sa.Column('title_en', sa.Text(), nullable=True))
    op.drop_column('abstracts', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abstracts', sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('abstracts', 'title_en')
    # ### end Alembic commands ###
