"""added auth-keyword flag to noun chunk

Revision ID: 66dee44a68c8
Revises: 9a7c3fab69f3
Create Date: 2018-06-25 00:08:37.790855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66dee44a68c8'
down_revision = '9a7c3fab69f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('keywords', 'from_keyword')
    op.add_column('noun_chunks', sa.Column('auth_keyword', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('noun_chunks', 'auth_keyword')
    op.add_column('keywords', sa.Column('from_keyword', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
