"""added doi field

Revision ID: 722b1410041c
Revises: a030e5747677
Create Date: 2018-06-24 20:16:23.547159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '722b1410041c'
down_revision = 'a030e5747677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abstracts', sa.Column('doi', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('abstracts', 'doi')
    # ### end Alembic commands ###
