"""added field of research

Revision ID: 7256a59924ab
Revises: fe9a604ad346
Create Date: 2018-06-24 22:43:13.378743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7256a59924ab'
down_revision = 'fe9a604ad346'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('abbr', sa.String(length=8), nullable=True),
    sa.Column('scopus_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('field_has_abstract',
    sa.Column('field_id', sa.Integer(), nullable=True),
    sa.Column('abstract_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['abstract_id'], ['abstracts.id'], ),
    sa.ForeignKeyConstraint(['field_id'], ['research_fields.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('field_has_abstract')
    op.drop_table('research_fields')
    # ### end Alembic commands ###
