"""added field scopus id to the author model

Revision ID: 822c5736e63c
Revises: 852e43032458
Create Date: 2018-06-24 20:05:03.881844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '822c5736e63c'
down_revision = '852e43032458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('scopus_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authors', 'scopus_id')
    # ### end Alembic commands ###
