"""added date of birth to scholarship info

Revision ID: 8eeb833af62b
Revises: 98af32e2c860
Create Date: 2019-04-25 09:21:30.243550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eeb833af62b'
down_revision = '98af32e2c860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scholarship_info', sa.Column('dob', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scholarship_info', 'dob')
    # ### end Alembic commands ###
