"""added university to scholarship info

Revision ID: 9164d7101ce1
Revises: ae87e616245c
Create Date: 2019-04-25 09:35:16.104901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9164d7101ce1'
down_revision = 'ae87e616245c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scholarship_info', sa.Column('university', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scholarship_info', 'university')
    # ### end Alembic commands ###
