"""added noun chunks to the model

Revision ID: 9b3e562ca76e
Revises: 5a746dbfb7e4
Create Date: 2018-06-24 19:34:25.909090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b3e562ca76e'
down_revision = '5a746dbfb7e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('noun_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chunk_en', sa.String(length=255), nullable=False),
    sa.Column('chuck_th', sa.String(length=255), nullable=False),
    sa.Column('abstract_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['abstract_id'], ['abstracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nounchunk_has_keyword',
    sa.Column('noun_chunk_id', sa.Integer(), nullable=True),
    sa.Column('keyword_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.ForeignKeyConstraint(['noun_chunk_id'], ['noun_chunks.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nounchunk_has_keyword')
    op.drop_table('noun_chunks')
    # ### end Alembic commands ###
