"""fixed mispelled col name

Revision ID: a030e5747677
Revises: 822c5736e63c
Create Date: 2018-06-24 20:14:11.773997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a030e5747677'
down_revision = '822c5736e63c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
