"""initial revision

Revision ID: aa93e8a6bb6e
Revises: 
Create Date: 2018-06-24 21:23:38.188013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa93e8a6bb6e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abstracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('title_en', sa.Text(), nullable=True),
    sa.Column('abstract_en', sa.Text(), nullable=True),
    sa.Column('title_th', sa.Text(), nullable=True),
    sa.Column('abstract_th', sa.Text(), nullable=True),
    sa.Column('scopus_id', sa.String(length=32), nullable=False),
    sa.Column('cited', sa.Integer(), nullable=True),
    sa.Column('pub_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scopus_id')
    )
    op.create_table('affils',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scopus_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('scopus_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('affil_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('affiliation_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['affiliation_id'], ['affils.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_en', sa.String(length=64), nullable=False),
    sa.Column('word_th', sa.String(length=64), nullable=False),
    sa.Column('abstract_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('scopus_id', sa.String(length=64), nullable=True),
    sa.Column('from_keyword', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['abstract_id'], ['abstracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keywords_first_name'), 'keywords', ['first_name'], unique=False)
    op.create_index(op.f('ix_keywords_last_name'), 'keywords', ['last_name'], unique=False)
    op.create_index(op.f('ix_keywords_word_en'), 'keywords', ['word_en'], unique=False)
    op.create_index(op.f('ix_keywords_word_th'), 'keywords', ['word_th'], unique=False)
    op.create_table('noun_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chunk_en', sa.String(length=255), nullable=False),
    sa.Column('chuck_th', sa.String(length=255), nullable=False),
    sa.Column('abstract_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['abstract_id'], ['abstracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nounchunk_has_keyword',
    sa.Column('noun_chunk_id', sa.Integer(), nullable=True),
    sa.Column('keyword_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.ForeignKeyConstraint(['noun_chunk_id'], ['noun_chunks.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nounchunk_has_keyword')
    op.drop_table('noun_chunks')
    op.drop_index(op.f('ix_keywords_word_th'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_word_en'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_last_name'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_first_name'), table_name='keywords')
    op.drop_table('keywords')
    op.drop_table('affil_history')
    op.drop_table('authors')
    op.drop_table('affils')
    op.drop_table('abstracts')
    # ### end Alembic commands ###
