"""replaced one-to-many between abstract and noun chunks to many-to-many

Revision ID: b9e7bb848b35
Revises: 7256a59924ab
Create Date: 2018-06-24 22:45:46.811465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9e7bb848b35'
down_revision = '7256a59924ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abstract_has_nounchunk',
    sa.Column('abstract_id', sa.Integer(), nullable=True),
    sa.Column('noun_chunk_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['abstract_id'], ['abstracts.id'], ),
    sa.ForeignKeyConstraint(['noun_chunk_id'], ['noun_chunks.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('abstract_has_nounchunk')
    # ### end Alembic commands ###
