"""added Thai title and abstract

Revision ID: bd48eaa9ddc6
Revises: 1918a9c4e971
Create Date: 2018-06-24 16:34:14.913930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd48eaa9ddc6'
down_revision = '1918a9c4e971'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abstracts', sa.Column('abstract_th', sa.Text(), nullable=True))
    op.add_column('abstracts', sa.Column('title_th', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('abstracts', 'title_th')
    op.drop_column('abstracts', 'abstract_th')
    # ### end Alembic commands ###
