"""renamed chuck_th to chunk_th

Revision ID: fe9a604ad346
Revises: 6ab74342e882
Create Date: 2018-06-24 22:22:49.609418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe9a604ad346'
down_revision = '6ab74342e882'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noun_chunks', sa.Column('chunk_th', sa.String(length=255), nullable=False))
    op.drop_column('noun_chunks', 'chuck_th')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noun_chunks', sa.Column('chuck_th', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('noun_chunks', 'chunk_th')
    # ### end Alembic commands ###
